/**
 * Canonical list of cattle breeds, keyed by upper-case breed code.
 * @type {Record<string, string>}
 */
export const breeds = {
  AA: 'Aberdeen Angus',
  AAX: 'Aberdeen Angus Cross',
  AB: 'Abondance',
  ABX: 'Abondance Cross',
  ALL: 'Australian Lowline',
  ALLX: 'Australian Lowline Cross',
  AR: 'Angler Rotvieh',
  ARX: 'Angler Rotvieh Cross',
  AN: 'Ankole',
  ANX: 'Ankole Cross',
  AM: 'Armoricaine',
  AMX: 'Armoricaine Cross',
  AU: 'Aubrac',
  AUX: 'Aubrac Cross',
  AY: 'Ayrshire',
  AYX: 'Ayrshire Cross',
  BRO: 'Baltata Romaneasca',
  BAZ: 'Bazadaise',
  BAZX: 'Bazadaise Cross',
  BEL: 'Beefalo',
  BSH: 'Beef Shorthorn',
  BSHX: 'Beef Shorthorn Cross',
  BG: 'Belted Galloway',
  BGX: 'Belted Galloway Cross',
  BWB: 'Belted Welsh Black',
  BWBX: 'Belted Welsh Black Cross',
  BI: 'Bison',
  BA: 'Blonde D’Aquitaine',
  BAX: 'Blonde D’Aquitaine Cross',
  BAL: 'Blue Albion',
  BALX: 'Blue Albion Cross',
  BLG: 'Blue Grey',
  BLGX: 'Blue Grey Cross',
  BR: 'Brahman',
  BRX: 'Brahman Cross',
  BP: 'Bretonne Pie-Noire',
  BPX: 'Bretonne Pie-Noire Cross',
  BRB: 'British Blue',
  BRBX: 'British Blue Cross',
  BF: 'British Friesian',
  BFX: 'British Friesian Cross',
  BW: 'British White',
  BWX: 'British White Cross',
  BS: 'Brown Swiss',
  BSX: 'Brown Swiss Cross',
  CH: 'Charolais',
  CHX: 'Charolais Cross',
  CHI: 'Chianina',
  CHIX: 'Chianina Cross',
  CHL: 'Chillingham',
  CHLX: 'Chillingham Cross',
  CB: 'Cross Breed Beef',
  CD: 'Cross Breed Dairy',
  CW: 'Coloured Welsh',
  CWX: 'Coloured Welsh Cross',
  DR: 'Danish Red',
  DRX: 'Danish Red Cross',
  DS: 'Dairy Shorthorn',
  DSX: 'Dairy Shorthorn Cross',
  DEV: 'Devon',
  DEVX: 'Devon Cross',
  DEX: 'Dexter',
  DEXX: 'Dexter Cross',
  DZE: 'Dwarf Zebu',
  EFB: 'East Finnish Brown',
  EFBX: 'East Finnish Brown Cross',
  ER: 'Estonian Red',
  ERX: 'Estonian Red Cross',
  FKV: 'Flekvieh',
  FKVX: 'Flekvieh Cross',
  FE: 'Frisona Espagnola',
  FEX: 'Frisona Espagnola Cross',
  GAS: 'Gasconne',
  GASX: 'Gasconne Cross',
  GA: 'Galloway',
  GAX: 'Galloway Cross',
  GE: 'Gelbvieh',
  GEX: 'Gelbvieh Cross',
  GL: 'Gloucester',
  GLX: 'Gloucester Cross',
  GB: 'Groninger Blaarkop',
  GBX: 'Groninger Blaarkop Cross',
  GU: 'Guernsey',
  GUX: 'Guernsey Cross',
  HK: 'Heck',
  HKX: 'Heck Cross',
  HE: 'Hereford',
  HEX: 'Hereford Cross',
  HI: 'Highland',
  HIX: 'Highland Cross',
  HO: 'Holstein',
  HOX: 'Holstein Cross',
  HF: 'Holstein Friesian',
  HFX: 'Holstein Friesian Cross',
  HS: 'Hungarian Steppe',
  HSX: 'Hungarian Steppe Cross',
  INRA: 'INRA95',
  INRAX: 'INRA95 Cross',
  IM: 'Irish Moiled',
  IMX: 'Irish Moiled Cross',
  JE: 'Jersey',
  JEX: 'Jersey Cross',
  KE: 'Kerry',
  KEX: 'Kerry Cross',
  LV: 'Lakenvelder',
  LVX: 'Lakenvelder Cross',
  LIM: 'Limousin',
  LIMX: 'Limousin Cross',
  LR: 'Lincoln Red',
  LRX: 'Lincoln Red Cross',
  LH: 'Longhorn',
  LHX: 'Longhorn Cross',
  LU: 'Luing',
  LUX: 'Luing Cross',
  MA: 'Maine Anjou',
  MAX: 'Maine Anjou Cross',
  MAC: 'Maraichine',
  MACX: 'Maraichine Cross',
  MAR: 'Marchigiana',
  MARX: 'Marchigiana Cross',
  MARE: 'Maremmana',
  MAREX: 'Maremmana Cross',
  MRI: 'Meuse Rhine Issel',
  MRIX: 'Meuse Rhine Issel Cross',
  MO: 'Montbeliarde',
  MOX: 'Montbeliarde Cross',
  MG: 'Murray Grey',
  MGX: 'Murray Grey Cross',
  NO: 'Normande',
  NOX: 'Normande Cross',
  NDS: 'Northern Dairy Shorthorn',
  NDSX: 'Northern Dairy Shorthorn Cross',
  NR: 'Norwegian Red',
  NRX: 'Norwegian Red Cross',
  OD: 'Other Dairy',
  PAJ: 'Pajuna',
  PAJX: 'Pajuna Cross',
  PA: 'Parthenais',
  PAX: 'Parthenais Cross',
  PI: 'Piemontese',
  PIX: 'Piemontese Cross',
  PR: 'Pie Rouge',
  PRX: 'Pie Rouge Cross',
  PIN: 'Pinzgauer',
  PINX: 'Pinzgauer Cross',
  RP: 'Red Poll',
  RPX: 'Red Poll Cross',
  RE: 'Reggiana',
  REX: 'Reggiana Cross',
  RG: 'Riggit Galloway',
  RGX: 'Riggit Galloway Cross',
  RO: 'Romagnola',
  ROX: 'Romagnola Cross',
  ROT: 'Rotebunde',
  ROTX: 'Rotebunde Cross',
  RF: 'Rouge Flamande',
  RFX: 'Rouge Flamande Cross',
  RUB: 'Rubia Gallega/Galician Blond',
  RUBX: 'Rubia Gallega/Galician Blond Cross',
  SA: 'Salers',
  SAX: 'Salers Cross',
  SH: 'Shetland',
  SHX: 'Shetland Cross',
  SM: 'Simmental',
  SMX: 'Simmental Cross',
  SD: 'South Devon',
  SDX: 'South Devon Cross',
  SP: 'Speckle Park',
  SPX: 'Speckle Park Cross',
  ST: 'Stabiliser',
  STX: 'Stabiliser Cross',
  SBW: 'Swedish Black and White',
  SBWX: 'Swedish Black and White Cross',
  SR: 'Swedish Red',
  SRX: 'Swedish Red Cross',
  SRP: 'Swedish Red Polled',
  SRW: 'Swedish Red and White',
  SRWX: 'Swedish Red and White Cross',
  SB: 'Swiss Braunvieh',
  SBX: 'Swiss Braunvieh Cross',
  SOB: 'Swiss Orig Braunvieh',
  SOBX: 'Swiss Orig Braunvieh Cross',
  SG: 'Swiss Grey',
  SGX: 'Swiss Grey Cross',
  SU: 'Sussex',
  SUX: 'Sussex Cross',
  TB: 'Tyrone Black',
  TBX: 'Tyrone Black Cross',
  VA: 'Vaynol',
  VAX: 'Vaynol Cross',
  WA: 'Wagyu',
  WAX: 'Wagyu Cross',
  BU: 'Water Buffalo',
  WB: 'Welsh Black',
  WBX: 'Welsh Black Cross',
  WW: 'Welsh White',
  WWX: 'Welsh White Cross',
  WG: 'White Galloway',
  WGX: 'White Galloway Cross',
  WS: 'Whitebred Shorthorn',
  WSX: 'Whitebred Shorthorn Cross',
  WP: 'White Park',
  WPX: 'White Park Cross',
  YK: 'Yak',
  YKX: 'Yak Cross',
  ZE: 'Zebu'
}

// Names use typographic apostrophes for display, but people type straight ones
// or leave them out, so names are compared lower-cased with apostrophes removed.
const normaliseName = (name) => name.toLowerCase().replace(/['‘’]/g, '')

const breedsByName = Object.fromEntries(
  Object.entries(breeds).map(([code, name]) => [normaliseName(name), code])
)

/**
 * @param {string} breedCode case-insensitive
 * @returns {string | undefined} the breed name, or undefined for an unknown code
 */
export const getBreedName = (breedCode) => {
  const key = breedCode?.toUpperCase()
  return Object.hasOwn(breeds, key) ? breeds[key] : undefined
}

/**
 * @param {string} breedName case-insensitive; apostrophes (straight, curly or none) are ignored
 * @returns {string | undefined} the breed code, or undefined for an unknown name
 */
export const getBreedCode = (breedName) => {
  const key = breedName && normaliseName(breedName)
  return Object.hasOwn(breedsByName, key) ? breedsByName[key] : undefined
}
