name: "Build"

on:
  push:
    branches:
      - feature/LREG-*
      - hotfix/LREG-*

permissions:
  contents: read

jobs:
  get-version:
    name: "Calculate Version"
    uses: ./.github/workflows/version.yml
    with:
      ref: ${{ github.ref_name }}

  build-pack:
    name: "Build, Test and Pack"
    needs: get-version
    uses: ./.github/workflows/build-pack.yml
    with:
      version: ${{ needs.get-version.outputs.version }}
      ref: ${{ github.ref_name }}

  sonar-analysis:
    name: "Sonar Analysis"
    needs: [get-version, build-pack]
    uses: ./.github/workflows/sonar.yml
    with:
      version: ${{ needs.get-version.outputs.version }}
      ref: ${{ github.ref_name }}
    secrets: inherit
